/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef shared_CONSTANTS_H
#define shared_CONSTANTS_H

#include "shared_types.h"

namespace shared {

class sharedConstants {
 public:
  sharedConstants();

};

extern const sharedConstants g_shared_constants;

} // namespace

#endif
