/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "shared_constants.h"

namespace shared {

const sharedConstants g_shared_constants;

sharedConstants::sharedConstants() {
}

} // namespace

